[package]
name = "advent_of_code_2015"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "d01"
path = "01/main.rs"

[[bin]]
name = "d02"
path = "02/main.rs"

[[bin]]
name = "dtest"
path = "dtest.rs"
