[package]
name = "advent_of_code_2018"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "d01"
path = "01/main.rs"

# dtest.rs is not included in the repo
# and is used to experiment with things
[[bin]]
name = "dtest"
path = "dtest.rs"
