[package]
name = "advent_of_code_2015"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "day_01"
path = "01/main.rs"

[[bin]]
name = "day_02"
path = "02/main.rs"

[[bin]]
name = "day_03"
path = "03/main.rs"

[[bin]]
name = "day_04"
path = "04/main.rs"

[dependencies]
md-5 = "0.10.6"
